{% set name = "pyupgrade" %}
{% set version = "3.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: defc292ffaf402942b8fccaa97491964063e343fc1993230e44890b971dc1234

build:
  noarch: python
  number: 0
  entry_points:
    - pyupgrade = pyupgrade._main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8.1
    - setuptools
  run:
    - python >=3.8.1
    - tokenize-rt >=5.2.0

test:
  commands:
    - pyupgrade --help

about:
  home: https://github.com/asottile/pyupgrade
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to automatically upgrade syntax for newer versions.

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
