{% set name = "pyupgrade" %}
{% set version = "3.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d10e8c5f54b8327211828769e98d95d95e4715de632a3414f1eef3f51357b9e2

build:
  noarch: python
  number: 0
  entry_points:
    - pyupgrade = pyupgrade._main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - tokenize-rt >=6.1.0

test:
  commands:
    - pyupgrade --help

about:
  home: https://github.com/asottile/pyupgrade
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to automatically upgrade syntax for newer versions.

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
