{% set name = "pyupgrade" %}
{% set version = "3.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e63a882ec1d16f5621736d938952df3cdc2446501fb049e711415cb8d273960

build:
  noarch: python
  number: 0
  entry_points:
    - pyupgrade = pyupgrade._main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - tokenize-rt >=6.1.0

test:
  requires:
    - python {{ python_min }}
  commands:
    - pyupgrade --help

about:
  home: https://github.com/asottile/pyupgrade
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to automatically upgrade syntax for newer versions.

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
